name: CI Pipeline

on:
  push:
    branches:
      - '*'
    paths:
      - 'Assigment-1/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Assigment-1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up C++ environment (for compilation)
      - name: Set up C++ environment
        uses: actions/setup-cpp@v1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libgtest-dev bash

      # Step 4: Build the project
      - name: Build the project using Makefile
        run: |
          make

      # Step 5: Run Google Test
      - name: Run Google Tests
        run: |
          make gtest

      - name: Add execute permissions to shell scripts
        run: |
          chmod +x tests/test_ascii.sh

      # Step 6: Run shell script test (ascii85.sh)
      - name: Run ASCII85 shell tests
        run: |
          bash tests/./test_ascii.sh

